CREATE TABLE USER_INFO 
(
  USER_ID NUMBER(5) 
, NAME VARCHAR2(20) 
, EMAIL VARCHAR2(20) 
);

COMMENT ON COLUMN USER_INFO.USER_ID IS '저장된 순서';

COMMENT ON COLUMN USER_INFO.NAME IS '유저 이름';

COMMENT ON COLUMN USER_INFO.EMAIL IS '유저 이메일';
